float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector
    run_groups:
      pgvector:
        arg_groups: [{M: 16, efConstruction: 40}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200]]
